version: '3'

services:

  receiver:
    build: mt-receive/ .
    depends_on:
      - sender
      - queue

  sender:
    build: mt-send/ .
    depends_on:
      - queue

  queue:
    image: "rabbitmq:3-management"
    ports:
    - "15672:15672"
    - "5672:5672"

  api:
    build: "API/ ."
    depends_on:
      - db
    ports:
    - "5000:80"
  
  db:
    image: redis
    ports:
      - "6379:6379"
  
  db-ui:
    image: marian/rebrow
    depends_on:
      - db
    ports:
      - "5001:5001"
  
