version: '3'

services:

  receiver:
    build: mt-receive/ .
    depends_on:
      - sender
      - queue

  sender:
    build: mt-send/ .
    depends_on:
      - queue

  queue:
    image: "rabbitmq:3-management"
    ports:
    - "15672:15672"
    - "5672:5672"