version: '3'

services:

  receiver:
    build: Receiver/ .
    depends_on:
      - queue
      - sender

  sender:
    build: Sender/ .
    depends_on:
      - queue

  queue:
    image: "rabbitmq:3-management"
    ports:
    - "15672:15672"
    - "5672:5672"

  api:
    build: "API/ ."
    depends_on:
      - redis
    ports:
    - "5000:80"
  
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  redis-ui:
    image: marian/rebrow
    depends_on:
      - redis
    ports:
      - "5001:5001"
  
