version: '3'
services:
  receiver:
    build: mt-receive/ .
    depends_on:
      - sender
  sender:
    build: mt-send/ .
    depends_on:
      - rabbit
  rabbit:
    image: "rabbitmq:3-management"
    ports:
    - "15673:15672"
    - "5673:5672"